# Generated by Django 4.2.8 on 2023-12-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleeper_avatar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
