# Generated by Django 4.2.8 on 2023-12-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleeper_league_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
