# Generated by Django 4.2.8 on 2023-12-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile_sleeper_league_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sleeper_league_name',
            new_name='sleeper_league_id',
        ),
    ]
