# Generated by Django 4.2.8 on 2023-12-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_sleeper_league_name_userprofile_sleeper_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sleeper_league_id',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
