# Generated by Django 4.2.8 on 2023-12-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_userprofile_sleeper_league_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('search_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('search_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=3, null=True)),
                ('fantasy_positions', models.JSONField(blank=True, null=True)),
                ('stats_id', models.IntegerField(blank=True, null=True)),
                ('yahoo_id', models.IntegerField(blank=True, null=True)),
                ('player_id', models.CharField(max_length=50, unique=True)),
                ('espn_id', models.IntegerField(blank=True, null=True)),
                ('oddsjam_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gsis_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sportradar_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rotowire_id', models.IntegerField(blank=True, null=True)),
                ('rotoworld_id', models.IntegerField(blank=True, null=True)),
                ('pandascore_id', models.IntegerField(blank=True, null=True)),
                ('fantasy_data_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
